[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1N6WUMvWnOibUWoBZ8sxk38dJwJjn0hyEifKislOdrfU/edit#gid=0"
type = "service_account"
project_id = "expense-splitter-492806"
private_key_id = "ca7dd76f2867b2b3a428f74731c1b9af2ba14e5b"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDF1Fgyzr2ijUTP
W9tlF/WW1tP0tfi62iIjovFUZr+XVqDfXMX3GuoaBHRHmM1UpPVwd2wHoImoEvLR
aXZt72aumQloxCpodujorm7aw0IQONPATrarU7PJe4W1VBpo1igUuYKHHjUO5QJD
NYvySayXkeke59H7NuCrcFHynbBWR5RENmoim7WPk6m72idIowHanTzZHKMPJY2i
GfgkqhOiZhX4VCtCxE287BQdTXR5Wvv122xPxG5UN4Gli8LKIqjULEST0jPpZ4R5
tOuPfkAeN0/gboKxgrOPF9lybRPooGVOk0djhz6t3ap+/5/k/h290uzbHZRp7Q4o
8yMVPq6tAgMBAAECggEAJbynZG2+i+MB1MJTfBnRbcgmH4CU5WPV7lFXUr/U3VQX
lPQYCVaXgIYH/l5eEL702NLXBy9vAuI2co75Geh4gGbN/i+pXUsNi9E2cUGc+QY2
EnGRc+YgHheTfm8AKK5tb+KhTRAMk/5Ia7SrsPiv1SvuucgD7LVfryRaZXsCF7ry
rrQ86svK5pDqtJfqnlCsoVYby85rtLkPIideG4d6lnkwRmLshXfNVEshbg/1IyXi
uuSQ8yVwKHpl+mX7Y8VDnkZIV5x1tL1V+8GCJApagmSsh8mdsuhyacT6n8ob5pbq
uoMVaz1NTFopvLNOy3wIEHM8eEDp7laxh7G/wu5bsQKBgQDx90QMYh+QygFfo58c
Jd5H/K5+/h44f8wupoZ65isa7Dp4RFTUDFpCKiJm1fAmauY1uMBG8RoTMgUDPeUm
FeHONxi/EvOMzAE1RscIPKsOZoBv3dbBSY2lIeDMnIfKGzGP+bFDird2iAtgwXVl
DvXOrldX8ieFuOf/r1wzYsTPiQKBgQDRTbycNSwC0AoJWsz2Ti9iatgKIDQWb23u
9LnzcU8qED7UQPX0H7qOi7lPjJIU6WbNCrHK0FFvrzwzdhP8rVwHqdNXrUTkAs8G
5q5o4yabxAm/zLveL9CpQ1x0XU8SRgdnrQBntZNU00b6PTdt0bR7ppSTf0ynM/s4
Qv2h0UBZBQKBgBQ4quoyBRtPln/Mp85tZ78yYc7hI9tq6sB3UEPTGoUceuJ0K3ax
NZXT+Z4IgRJk2qpgr0j+e0RhaMPVl2HwcDeQqTPGvK3mmq8+JAIPN+hzLoaqznjG
0dycETJoXnzIewLiRisz25M/WVwTruDsOCS2szv5U848Hr9ig10UAwipAoGAFg/X
na+NIA7FwA6uJBhBrmIMu6SBWQwNzm5FW3/KFGj59m2Sf1UI2RWpRtVOYJ3plBtY
ekRTES6rbdE4ch3j4XrpKAi/hjk1kUinga7P1wNm86yk8NqhZ/YNvMZJG2f+R9NY
g5YEHaDXjnD9crn0CESazKFSdx1nkZqeGXxxB/ECgYAS4K/22EEMg1b6MUGs8Tr9
2mJyVrfarYHM1XqrWhRaXQsA00YqK7BTSpP6hRbuzBfRLpmct7Z3vOJhyBR+JGZW
t24M+brOmKet2LMsfDAgfcigGfRU4NINxSzoKsMCzhYffQQqjbZyZk/Rt7KT6axM
MnyuK4jcDGc5Klr0SYGn9Q==
-----END PRIVATE KEY-----
"""
client_email = "trip-bot@expense-splitter-492806.iam.gserviceaccount.com"
client_id = "104541143216914642776"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/trip-bot%40expense-splitter-492806.iam.gserviceaccount.com"
universe_domain = "googleapis.com"